### ISSUE TITLE
Move to Drupal.org?

### ISSUE THREAD

**Issue by nerdstein** [lukaswhite/Drupal-Jekyll-Export#6]
This seems to be a module, I was curious why this is not up on Drupal.org.

**Comment by lukaswhite** [comment]
I don't know if it's still the case, but when I wrote this I didn't have the ability to publish modules on Drupal.org because you needed your first module to be reviewed before being given that privilege - I was stuck in a queue waiting for my first contribution to be waved through. It ended up taking months, and by the time it had happened I'd lost the motivation to contribute to the ecosystem in general. 

Also, it's only really a quick and dirty, one-time "helper" module, so it doesn't really seem worth it.

If someone wants to take this forward via Drupal.org then go right ahead, but I don't really have any interest in doing so.

**Comment by nerdstein** [comment]
That process has actually changed. Anyone can create projects now. I'd encourage you to try again, I bet you would be pleasantly surprised by how many people would use/contribute to it.
